### ISSUE TITLE
Text underneath menu banner when clicking footnote return (↩)

### ISSUE THREAD

**Issue by Tele-Pet** [getgrav/grav-theme-antimatter#16]
In order to use Markdown footnotes, my **user/config/site.yaml** includes the setting: 
`markdown_extra: true`

When I click the ↩ for a given footnote, it scrolls upwards, but the text is now beneath the menu banner.  I see this behavior on both Safari and Chrome browsers, on a Mac.

![footnote_issue](https://cloud.githubusercontent.com/assets/6935316/9153387/9bb64cee-3e20-11e5-9c35-f09d96784853.png)

**Comment by rhukster** [comment]
Sorry for the delay, can you please provide me your markdown code for this page so I can test and replicate it as close as possible??

**Comment by Tele-Pet** [comment]
No worries at all.  Here is the [link](http://www.kontele.com/portfolio/map_redesign#fnref1:fn1) to the page in question, and here is the Markdown:

```
---
title: Map Redesign
---

### Scenario
Members of the community and local law enforcement will be meeting to discuss issues surrounding graffiti.  The old map is outdated and lacking in clarity, so an updated map is required.

### Solution
* Retrieve current [graffiti data](https://nycopendata.socrata.com/data?browseSearch=graffiti) and import into a GIS[^fn1] as points layer
* Overlay the graffiti points with a hexagonal grid and collect a count of graffiti instances within a given hexagon
* Employ a graduated styling of the hexagonal grid based on number of graffiti instances.

![][reg_view]





<!-- Footnotes   -->
[^fn1]: [QGIS](http://qgis.org/en/site/) and [select plugins](http://michaelminn.com/linux/mmqgis/) employed to create grid shapefile, which was then imported into an [ArcGIS](http://www.esri.com/software/arcgis) project.

<!-- Resource links:   -->
[reg_view]: map_redesign.jpg

```

**Comment by rhukster** [comment]
Sorry for the delay, I really don't know how to fix this, or if it's even possible at all.  The problem is that inline anchors are controlled by the browser, so you have to put some spacing in the HTML to offset (typically the solution with page anchors).  However, this being a `<sup>` means i can't add arbitrary spacing as it changes the layout of the page. 

The only real option available if this is important to you is to remove the fixed header, and just have it scroll with the page like a normal element.
